# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source $HOME/.git-prompt.sh
source $HOME/.bash_completion/*.sh

export EDITOR="/usr/bin/vim"
export PAGER="/usr/bin/less"
export LANG="en_US.UTF-8"
export PACMAN=/usr/bin/pacman 
[ -f /usr/bin/pacman-color ] && export PACMAN=/usr/bin/pacman-color

alias cal='cal -3'
alias df='df -h'
alias du='du -sh'
alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
alias l.='ls -dF .* --color=auto'
alias la='ls -hA --color=auto'
alias less='less -R'
alias ll='ls -lFh --color=auto'
alias lla='ls -lhA --color=auto'
alias lld='ls -ldFh --color=auto'
alias ls='ls -hF --color=auto'
alias mkdir='mkdir -p -v'

# Optional aliases
#alias top='htop'
#alias yogurt='yaourt'

## Arch Linux specific aliases
alias pacman='$PACMAN'

# Pacman alias examples
# Synchronize with repositories before upgrading packages that are out of date on the local system.
alias pacupg='sudo $PACMAN -Syu'
# Install specific package(s) from the repositories
alias pacin='sudo $PACMAN -S'
# Install specific package not from the repositories but from a file
alias pacins='sudo $PACMAN -U'
# Remove the specified package(s), retaining its configuration(s) and required dependencies
alias pacre='sudo $PACMAN -R'
# Remove the specified package(s), its configuration(s) and unneeded dependencies
alias pacrem='sudo $PACMAN -Rns'
# Display information about a given package in the repositories
alias pacrep='$PACMAN -Si'
# Search for package(s) in the repositories
alias pacreps='$PACMAN -Ss'
# Display information about a given package in the local database
alias pacloc='$PACMAN -Qi'
# Search for package(s) in the local database
alias paclocs='$PACMAN -Qs'




eval $(dircolors $HOME/.dir_colors)

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Enable history appending instead of overwriting.  #139609
shopt -s histappend

# Disable Ctrl-S and Ctrl-Q from terminal sessions
stty -ixon

# Local change support

[[ -r $HOME/.bashrc_local ]] && source $HOME/.bashrc_local

if [ $TERM != "screen-256color" ] && [  $TERM != "screen" ]; then
    if tmux has-session -t main 2>/dev/null; then
        tmux attach -t main
    else
        tmux new -s main
    fi
fi


