alias cal='cal -3'
alias df='df -h'
alias du='du -sh'
alias less='less -R'
alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
alias l.='ls -dF .* --color=auto'
alias ll='ls -lFh --color=auto'
alias lld='ls -ldFh --color=auto'
alias ls='ls -hF --color=auto'
alias la='ls -hA --color=auto'
alias lla='ls -lhA --color=auto'
alias pacman='pacman-color'
alias top='htop'
alias yogurt='yaourt'

